### ISSUE TITLE
traversing over an Array with the `each` extension and `$item` for text is broken

### ISSUE THREAD

**Issue by daanvanham** [konfirm/kontext#5]
It looks like `$item` does not work (anymore), not rendering the actual text but only rendering the correct amount of DOMNodes.

Somewhere in the model:
```
loop: ['test', 'another', 'thing']
```

HTML:
```
<ul data-kontext="each: loop">
    <li data-kontext="text: $item"></li>
</ul>
```

Renders (removed `data-kontext` attributes for readability):
```
<ul>
    <li></li>
    <li></li>
    <li></li>
</ul>
```

Expected (removed `data-kontext` attributes for readability):
```
<ul>
    <li>test</li>
    <li>another</li>
    <li>thing</li>
</ul>
```

**Comment by rspieker** [comment]
The issue is resolved, I will leave the issue open until it is released.
